### ISSUE TITLE
运行结果

### ISSUE THREAD

**Issue by yearlong0528** [AnAppleCore/MOSE#1]
作者您好，请问你们提供的源码跑出来的最后的结果，last_test_acc代表的是mose，test_acc代表的是moe-mose吗

**Comment by AnAppleCore** [comment]
是的没错，`last_test_acc`是MOSE的输出结果，指网络最后一层的常规输出。`test_acc`是MOE-MOSE，是所有expert输出的平均结果

**Comment by yearlong0528** [comment]
感谢解答🙏

**Comment by AnAppleCore** [comment]
不用谢，希望对你有所帮助😉
