### ISSUE TITLE
4个专家的表现差异

### ISSUE THREAD

**Issue by ooooooover** [AnAppleCore/MOSE#3]
![image](https://github.com/AnAppleCore/MOSE/assets/106066982/90164176-c6d3-4c53-bc50-cd11c757ba3c)
请问为什么最后一个专家（也就是网络的输出）会只在最后一个任务上表现得最好呢，他在最后一个任务表现好是有什么理论依据还是单纯的实现现象呢，期待您的回复

**Comment by AnAppleCore** [comment]
你好！这里`最后一个专家相比其他专家只在最后一个任务上表现最好`是实验记录的结果，一个直观的理解是：持续学习场景中的recency bias对于网络深层的部分影响更大。先前有一些工作对这种bias做出过描述并提出了解决方案[Sungmin et al](https://arxiv.org/pdf/2201.12559)，[Aristotelis et al](https://openreview.net/pdf?id=Ph65E1bE6A)和[Yilin et al](https://proceedings.neurips.cc/paper_files/paper/2023/file/50ca96a1a9ebe0b5e5688a504feb6107-Paper-Conference.pdf)，等等。一般来说，这种bias影响最大的是基于cross-entropy优化的最后一层fully connected classifier，我个人认为这里最后一个专家相对浅层的部分更偏向于新到来的任务，可以用相似的理论去解释。

**Comment by ooooooover** [comment]
好的 感谢您的回答
