### ISSUE TITLE
关于 Reverse Self-Distillation

### ISSUE THREAD

**Issue by vk-rrr** [AnAppleCore/MOSE#4]
您好，请问在 Reverse Self-Distillation 时，是如何对齐学生与教师特征的通道数？

**Comment by AnAppleCore** [comment]
我们在得到每个学生的feature_map之后，加入了降采样的辅助downsampling convolution，一边降低feature map的空间维度大小，一边提升channel数量。具体代码请参考[./models/Resnet18_SD.py](https://github.com/AnAppleCore/MOSE/blob/master/models/Resnet18_SD.py)中的`DownConv`和`_make_feature_layer`。

**Comment by vk-rrr** [comment]
好的，感谢您的解答

**Comment by AnAppleCore** [comment]
希望对你有所帮助 ;)
